const data = [
    {
        deviceType: '1',
        name: 'T001型柱式路灯',
        deviceId: 'ZX001',
        poiName: '邮电大学体育馆东路',
        state: '1',
        countDown: '0',
    },
    {
        deviceType: '1',
        name: 'T001型柱式路灯',
        deviceId: 'ZX002',
        poiName: '邮电大学体育馆西路',
        state: '-1',
        countDown: '0',
    },
    {
        deviceType: '1',
        name: 'T001型柱式路灯',
        deviceId: 'ZX003',
        poiName: '邮电大学体育馆东路',
        state: '0',
        countDown: '10000',
    },
    {
        deviceType: '1',
        name: 'T001型柱式路灯',
        deviceId: 'ZX004',
        poiName: '政法大学求职路',
        state: '1',
        countDown: '0',
    },
    {
        deviceType: '1',
        name: 'T001型柱式路灯',
        deviceId: 'ZX005',
        poiName: '政法大学书香路',
        state: '0',
        countDown: '4000',
    },
    {
        deviceType: '1',
        name: 'T001型柱式路灯',
        deviceId: 'ZX006',
        poiName: '西长安街',
        state: '1',
        countDown: '0',
    },
    {
        deviceType: '2',
        name: 'T002型悬挂路灯',
        deviceId: 'ZX007',
        poiName: '政法大学寻思路',
        state: '1',
        countDown: '0',
    },
    {
        deviceType: '2',
        name: 'T002型悬挂路灯',
        deviceId: 'ZX008',
        poiName: '政法大学求职路',
        state: '0',
        countDown: '300',
    },
    {
        deviceType: '1',
        name: 'T001型柱式路灯',
        deviceId: 'ZX006',
        poiName: '西长安街',
        state: '1',
        countDown: '0',
    },
    {
        deviceType: '2',
        name: 'T002型悬挂路灯',
        deviceId: 'ZX007',
        poiName: '政法大学寻思路',
        state: '1',
        countDown: '0',
    },
    {
        deviceType: '2',
        name: 'T002型悬挂路灯',
        deviceId: 'ZX008',
        poiName: '政法大学求职路',
        state: '0',
        countDown: '300',
    },
    {
        deviceType: '1',
        name: 'T001型柱式路灯',
        deviceId: 'ZX006',
        poiName: '西长安街',
        state: '1',
        countDown: '0',
    },
    {
        deviceType: '2',
        name: 'T002型悬挂路灯',
        deviceId: 'ZX007',
        poiName: '政法大学寻思路',
        state: '1',
        countDown: '0',
    },
    {
        deviceType: '2',
        name: 'T002型悬挂路灯',
        deviceId: 'ZX008',
        poiName: '政法大学求职路',
        state: '0',
        countDown: '300',
    },
]
module.exports = {
    data,
}